version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - YAYA_WEBHOOK_SECRET=${YAYA_WEBHOOK_SECRET}
    ports:
      - "8500:8000"
    depends_on:
      - db

volumes:
  postgres_data:
