# Generated by Django 5.1.2 on 2024-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookPayload',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at_time', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('cause', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('invoice_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
