# Generated by Django 5.1.2 on 2024-10-28 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_webhookpayload_delete_webhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookpayload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
